from typing import Protocol


class FootballDataProtocol(Protocol):
    def teams(self) -> list: ...
    def squad(self, team_id: int) -> list: ...
    def player_stats(self, team_id: int) -> list: ...
    def fixtures(self, team_id: int | None = None) -> list: ...
    def standings(self, group: str | None = None) -> list: ...
    def injuries(self, team_id: int) -> list: ...
    def live(self) -> list: ...
    def find_team_id(self, name: str) -> int | None: ...
